# Generated by Django 3.2.5 on 2021-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210728_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='RAM',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='flashMemory',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
