# Generated by Django 3.2.5 on 2021-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210731_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='RAM',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='flashMemory',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
