export const PHONE_LIST_REQUEST = 'PHONE_LIST_REQUEST'
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS'
export const PHONE_LIST_FAIL = 'PHONE_LIST_FAIL'

export const PHONE_DETAILS_REQUEST = 'PHONE_DETAILS_REQUEST'
export const PHONE_DETAILS_SUCCESS = 'PHONE_DETAILS_SUCCESS'
export const PHONE_DETAILS_FAIL = 'PHONE_DETAILS_FAIL'

export const PHONE_FILTER_VALUES_REQUEST = 'PHONE_FILTER_VALUES_REQUEST'
export const PHONE_FILTER_VALUES_SUCCESS = 'PHONE_FILTER_VALUES_SUCCESS'
export const PHONE_FILTER_VALUES_FAIL = 'PHONE_FILTER_VALUES_FAIL'

export const PHONE_FILTER_LIST_REQUEST = 'PHONE_FILTER_LIST_REQUEST'
export const PHONE_FILTER_LIST_SUCCESS = 'PHONE_FILTER_LIST_SUCCESS'
export const PHONE_FILTER_LIST_FAIL = 'PHONE_FILTER_LIST_FAIL'

export const PHONE_DELETE_REQUEST = 'PHONE_DELETE_REQUEST'
export const PHONE_DELETE_SUCCESS = 'PHONE_DELETE_SUCCESS'
export const PHONE_DELETE_FAIL = 'PHONE_DELETE_FAIL'

export const PHONE_CREATE_REQUEST = 'PHONE_CREATE_REQUEST'
export const PHONE_CREATE_SUCCESS = 'PHONE_CREATE_SUCCESS'
export const PHONE_CREATE_FAIL = 'PHONE_CREATE_FAIL'
export const PHONE_CREATE_RESET = 'PHONE_CREATE_RESET'

export const PHONE_UPDATE_REQUEST = 'PHONE_UPDATE_REQUEST'
export const PHONE_UPDATE_SUCCESS = 'PHONE_UPDATE_SUCCESS'
export const PHONE_UPDATE_FAIL = 'PHONE_UPDATE_FAIL'
export const PHONE_UPDATE_RESET = 'PHONE_UPDATE_RESET'

export const PHONE_CREATE_REVIEW_REQUEST = 'PHONE_CREATE_REVIEW_REQUEST'
export const PHONE_CREATE_REVIEW_SUCCESS = 'PHONE_CREATE_REVIEW_SUCCESS'
export const PHONE_CREATE_REVIEW_FAIL = 'PHONE_CREATE_REVIEW_FAIL'
export const PHONE_CREATE_REVIEW_RESET = 'PHONE_CREATE_REVIEW_RESET'

export const PHONE_TOP_REQUEST = 'PHONE_TOP_REQUEST'
export const PHONE_TOP_SUCCESS = 'PHONE_TOP_SUCCESS'
export const PHONE_TOP_FAIL = 'PHONE_TOP_FAIL'
