export const PHONE_LIST_REQUEST = 'PHONE_LIST_REQUEST'
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS'
export const PHONE_LIST_FAIL = 'PHONE_LIST_FAIL'

export const PHONE_DETAILS_REQUEST = 'PHONE_DETAILS_REQUEST'
export const PHONE_DETAILS_SUCCESS = 'PHONE_DETAILS_SUCCESS'
export const PHONE_DETAILS_FAIL = 'PHONE_DETAILS_FAIL'
